# Generated by Django 3.0.6 on 2020-05-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrequesntlyAskedQuestions',
            new_name='FrequentlyAskedQuestions',
        ),
    ]
